### ISSUE TITLE
Weiterleitung

### ISSUE THREAD

**Issue by profemo** [CoderDojoPotsdam/OLD-CoderDojoPotsdam.github.io#1]
Irgendwas ist da komisch. 
coderdojopotsdam.github.io/CoderDojoPotsdam.github.io
und
coderdojopotsdam.github.io
führen nach der Weiterleitung auf ne 404 bei ze.coderdoj...

https://zen.coderdojo.com/dojo/861 aufgerufen funktioniert wieder.

https://zen.coderdojo.com/dojo/de/brandenburg/potsdam/potsdam-hpi funktioniert auch wenn es direkt aufgerufen wird.

Keine Ahnung was da der genaue Fehler ist. Ihr anscheinend auch nicht. Sonst hättet ihr es schon gelöst. Vielleicht mal auf den Stand mit der alten URL zurück setzen?

viele Glück!

**Comment by niccokunzmann** [comment]
@profemo Dankeschön für den Hinweis! Ich habe es jetzt auf die neue URL gesetzt. Wenn es sich nochmal ändert, können wir ja die alte URL benutzen. Die ging auch eine Weile nicht. [Für die Zen Webseite](https://github.com/CoderDojo/community-platform/issues) gibt es auch eine Issue, glaube ich, die static URLs für die Dojos behandeln sollte.
